name: DC_CI/CD
on: [push]
env:
  msk-ci-cd: Release
jobs:
  DC-service-on-EC2:
    runs-on: ubuntu-latest
    steps:
      runs :
        using: 'docker'
        image: 'Dockerfile'
        - run: docker build -t dc_app .
      
