name: DC_CI/CD
on: [push]
env:
  msk-ci-cd: Release
jobs:
  DC-service-on-EC2:
    runs-on: ubuntu-latest
    steps:
      - name: check out source code
        uses: actions/checkout@v2
      - name: Run docker compose
        run: docker-compose up -d