name: DC_CI/CD
on: [push]
env:
  msk-ci-cd: Release
jobs:
  DC-service-on-EC2:
    runs-on: self-hosted
    steps:
      - name: check out source code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t dc-app .
      - name: List docker image 
        run: docker image ls
      - name: Run docker container
        run: docker-compose up
      - name : watch docker process 
        run: docker ps
      # - name: Run docker compose
      #   run: docker-compose up