name: DC_CI/CD
on: [push]
env:
  msk-ci-cd: Release
jobs:
  DC-service-on-EC2:
    runs-on: self-hosted
    steps:
      - name: check out source code
        uses: actions/checkout@v2
      - name: Build docker image
        run: sudo docker build -t dc-app .
      - name: List docker image 
        run: sudo docker image ls
      - name: Run docker container
        run: sudo docker-compose up -d
      - name : watch docker process 
        run: sudo docker ps
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      # - name: Run docker compose
      #   run: docker-compose up